cam = nil
cardimensions = nil
ammountwheels = 0
bonePos = vector3(0, 0, 0)
carvelocity = vector3(0, 0, 0)
carfwdvec = vector3(0, 0, 0)
globaldeltatime = 0
wheellfbone = 0
wheellrbone = 0
isonwheelie = false
isflying = nil
driftvibrationfactor = nil
jumped = false
airtime = airtime or 0
modelDimMin = 0
modelDimMax = 0
wheeliefactor = 0
bikerw = 0
bikefw = 0
frontwheelheightoffset = 0
lockcamposition = false
vehicleData = vehicleData or {}
currentYOffset = currentYOffset or 0
currentXOffset = currentXOffset or 0
currentYOffsetpitch = currentYOffsetpitch or 0
currentZOffset = currentZOffset or 0
currentorbx = nil
currentorby = nil
attachpointx = nil
attachpointy = nil
lastGForceZ = lastGForceZ or 0
currentpitch = 0
currentroll = 0
currentcameradriftangle = 0
previousHeading = nil
previousCameraPosition = nil
previousXOffset = 0
previousyaw = 0
currentmomentum = 1
yOffset = 0
testzoffset = testzoffset or 0
currentlock = nil
prevpos = nil
bonePosVelocityX = 0
bonePosVelocityY = 0
bonePosVelocityZ = 0
quatVelocityW = 0
quatVelocityX = 0
quatVelocityY = 0
quatVelocityZ = 0
diffx = 0
diffy = 0
currentslipangle = 0
truedeltatime = 0
targetx = nil
targety = nil
shiftedlerpfactor = camerasettings[0].interpolationfactor
currentlerpfactor = shiftedlerpfactor
currentxvibration = 0
currentyvibration = 0
camzoffset = 0
fovdebug = 0
fovdebuginjection = 0
accpitchdebug = 0
coastpitchdebug = 0
brakingpitchdebug = 0
basepitchdebug = 0
accpitchdebuginjection = 0
coastpitchdebuginjection = 0
brakingpitchdebuginjection = 0
basepitchdebuginjection = 0
currentdriftzboost = 0
camhoodzoffset = 0
camhoodyoffset = 0
interpolationoffset = 0
camhoodz = 0
camhoody = 0
lerpedangularvelocity = 0
isonfpvcam = false
disablehoodcamblur = false
orbitheading = 0
movedmousetime = 0
currentmouse = 0
currentmousespeed = 0
cameradata = 0
currentcamera = 0
forcebikemode = false
